// @generated by scripts/generate_lowering_tables.py - do not edit manually.
//
// Source of truth: packages/spectra-contract/catalog/stdlib.toml
// Regenerate:      python scripts/generate_lowering_tables.py
// Verify:          python scripts/generate_lowering_tables.py --check
//
// `std.collections` (map/stack/queue/set/iterator) and `std.string` descriptors.
//
// Arm order, section comments and the helper-vs-literal rendering style are
// presentation data owned by the generator (see LAYOUT); runtime names, IR
// return types and `returns_value` come from the catalog.

use super::*;

pub(crate) fn lookup_std_host_group_collections_string(
    module: &str,
    function: &str,
) -> Option<HostFunctionDescriptor> {
    match (module, function) {
        // ── std.collections map ──────────────────────────────────────
        ("collections", "map_new") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.map_new",
            return_type: IRType::Struct {
                name: "Map_int_int".to_string(),
                fields: Vec::new(),
            },
            returns_value: true,
        }),
        ("collections", "map_set") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.map_set",
            return_type: IRType::Int,
            returns_value: false,
        }),
        ("collections", "map_get") => Some(HostFunctionDescriptor {
            runtime_name: spectra_contract::STD_COLLECTIONS_MAP_GET_BINDING,
            return_type: IRType::Unknown,
            returns_value: true,
        }),
        ("collections", "map_get_option") => Some(HostFunctionDescriptor {
            runtime_name: spectra_contract::STD_COLLECTIONS_MAP_GET_OPTION_BINDING,
            return_type: IRType::Unknown,
            returns_value: true,
        }),
        ("collections", "map_contains") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.map_contains",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("collections", "map_remove") => Some(HostFunctionDescriptor {
            runtime_name: spectra_contract::STD_COLLECTIONS_MAP_REMOVE_BINDING,
            return_type: IRType::Unknown,
            returns_value: true,
        }),
        ("collections", "map_remove_option") => Some(HostFunctionDescriptor {
            runtime_name: spectra_contract::STD_COLLECTIONS_MAP_REMOVE_OPTION_BINDING,
            return_type: IRType::Unknown,
            returns_value: true,
        }),
        ("collections", "map_len") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.map_len",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("collections", "map_is_empty") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.map_is_empty",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("collections", "map_clear") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.map_clear",
            return_type: IRType::Int,
            returns_value: false,
        }),
        ("collections", "map_free") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.map_free",
            return_type: IRType::Void,
            returns_value: false,
        }),
        ("collections", "map_free_all") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.map_free_all",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("collections", "map_values_iter") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.map_values_iter",
            return_type: IRType::Struct {
                name: "Iterator_int".to_string(),
                fields: Vec::new(),
            },
            returns_value: true,
        }),
        // ── std.collections set/iterator ──────────────────────────────
        ("collections", "set_new") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.set_new",
            return_type: IRType::Struct {
                name: "Set_int".to_string(),
                fields: Vec::new(),
            },
            returns_value: true,
        }),
        ("collections", "set_insert") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.set_insert",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("collections", "set_contains") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.set_contains",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("collections", "set_remove") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.set_remove",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("collections", "set_len") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.set_len",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("collections", "set_get") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.set_get",
            return_type: IRType::Unknown,
            returns_value: true,
        }),
        ("collections", "set_clear") => Some(host_void("spectra.std.collections.set_clear")),
        ("collections", "set_free") => Some(host_void("spectra.std.collections.set_free")),
        ("collections", "list_iter") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.list_iter",
            return_type: IRType::Struct {
                name: "Iterator_int".to_string(),
                fields: Vec::new(),
            },
            returns_value: true,
        }),
        ("collections", "set_iter") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.set_iter",
            return_type: IRType::Struct {
                name: "Iterator_int".to_string(),
                fields: Vec::new(),
            },
            returns_value: true,
        }),
        ("collections", "map_iter") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.map_iter",
            return_type: IRType::Struct {
                name: "Iterator_int".to_string(),
                fields: Vec::new(),
            },
            returns_value: true,
        }),
        ("collections", "iterator_next") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.iterator_next",
            return_type: IRType::Unknown,
            returns_value: true,
        }),
        ("collections", "iterator_remaining") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.iterator_remaining",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("collections", "iterator_free") => {
            Some(host_void("spectra.std.collections.iterator_free"))
        }
        ("collections", "stack_new") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.stack_new",
            return_type: IRType::Struct {
                name: "Stack_int".to_string(),
                fields: Vec::new(),
            },
            returns_value: true,
        }),
        ("collections", "stack_push") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.stack_push",
            return_type: IRType::Void,
            returns_value: false,
        }),
        ("collections", "stack_pop") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.stack_pop",
            return_type: IRType::Unknown,
            returns_value: true,
        }),
        ("collections", "stack_peek") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.stack_peek",
            return_type: IRType::Unknown,
            returns_value: true,
        }),
        ("collections", "stack_len") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.stack_len",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("collections", "stack_is_empty") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.stack_is_empty",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("collections", "stack_clear") => Some(host_void("spectra.std.collections.stack_clear")),
        ("collections", "stack_free") => Some(host_void("spectra.std.collections.stack_free")),
        ("collections", "stack_free_all") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.stack_free_all",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("collections", "stack_iter") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.stack_iter",
            return_type: IRType::Struct {
                name: "Iterator_int".to_string(),
                fields: Vec::new(),
            },
            returns_value: true,
        }),
        ("collections", "queue_new") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.queue_new",
            return_type: IRType::Struct {
                name: "Queue_int".to_string(),
                fields: Vec::new(),
            },
            returns_value: true,
        }),
        ("collections", "queue_enqueue") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.queue_enqueue",
            return_type: IRType::Void,
            returns_value: false,
        }),
        ("collections", "queue_dequeue") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.queue_dequeue",
            return_type: IRType::Unknown,
            returns_value: true,
        }),
        ("collections", "queue_peek") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.queue_peek",
            return_type: IRType::Unknown,
            returns_value: true,
        }),
        ("collections", "queue_len") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.queue_len",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("collections", "queue_is_empty") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.queue_is_empty",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("collections", "queue_clear") => Some(host_void("spectra.std.collections.queue_clear")),
        ("collections", "queue_free") => Some(host_void("spectra.std.collections.queue_free")),
        ("collections", "queue_free_all") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.queue_free_all",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("collections", "queue_iter") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.collections.queue_iter",
            return_type: IRType::Struct {
                name: "Iterator_int".to_string(),
                fields: Vec::new(),
            },
            returns_value: true,
        }),
        // ── std.string ────────────────────────────────────────────────
        ("string", "len") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.len",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("string", "contains") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.contains",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("string", "to_upper") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.to_upper",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "to_lower") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.to_lower",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "trim") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.trim",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "starts_with") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.starts_with",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("string", "ends_with") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.ends_with",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("string", "eq") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.eq",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("string", "concat") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.concat",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "repeat_str") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.repeat_str",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "char_at") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.char_at",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("string", "substring") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.substring",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "replace") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.replace",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "index_of") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.index_of",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("string", "split_first") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.split_first",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "split_last") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.split_last",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "is_empty") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.is_empty",
            return_type: IRType::Bool,
            returns_value: true,
        }),
        ("string", "count_occurrences") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.count_occurrences",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("string", "reverse_str") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.reverse_str",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "pad_left") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.pad_left",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "pad_right") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.pad_right",
            return_type: IRType::String,
            returns_value: true,
        }),
        // ── std.string string builder (R-3108) ────────────────────────
        ("string", "builder_new") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.builder_new",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("string", "builder_push") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.builder_push",
            return_type: IRType::Void,
            returns_value: false,
        }),
        ("string", "builder_len") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.builder_len",
            return_type: IRType::Int,
            returns_value: true,
        }),
        ("string", "builder_finish") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.builder_finish",
            return_type: IRType::String,
            returns_value: true,
        }),
        ("string", "builder_free") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.builder_free",
            return_type: IRType::Void,
            returns_value: false,
        }),
        ("string", "split_by") => Some(HostFunctionDescriptor {
            runtime_name: "spectra.std.string.split_by",
            return_type: IRType::Struct {
                name: "List_string".to_string(),
                fields: Vec::new(),
            },
            returns_value: true,
        }),
        // ── std.convert ───────────────────────────────────────────────
        _ => None,
    }
}
