#!/usr/bin/env python3
"""Generate the `spectra-api` host-call table from the typed STD/API catalog.

The catalog (``packages/spectra-contract/catalog/stdlib.toml``) is the single
source of truth for every native function: it already carries the Rust symbol
(``rust_symbol``) and the compile-time gate (``cfg_feature``) that the host-call
table used to duplicate by hand.  This generator reads those two fields in
catalog order and renders ``packages/spectra-api/src/host_calls.rs``.

Only ``kind = "function"`` entries with a ``rust_symbol`` produce a
``HostCallSpec``; every such binding must live in the ``spectra.api.``
namespace.  Entries with ``cfg_feature`` are emitted behind a
``#[cfg(feature = "...")]`` attribute, so the gated entries disappear from the
table (and from ``HOST_CALLS.len()``) when the feature is off.

``--check`` re-renders the table in memory and fails when the file on disk is
stale, which is how the validation script catches a hand edit of a generated
file.

Usage:
    python scripts/generate_host_calls.py
    python scripts/generate_host_calls.py --check
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = "packages/spectra-contract/catalog/stdlib.toml"
OUTPUT = "packages/spectra-api/src/host_calls.rs"
HOST_CALL_PREFIX = "spectra.api."
# Rust paths used as `function:` values: `symbol`, `module::symbol`, or
# `module::submodule::symbol`.
RUST_SYMBOL_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*(::[A-Za-z_][A-Za-z0-9_]*)*$")

HEADER = """\
// @generated by scripts/generate_host_calls.py - do not edit manually.
//
// Source of truth: packages/spectra-contract/catalog/stdlib.toml
// Regenerate:      python scripts/generate_host_calls.py
// Verify:          python scripts/generate_host_calls.py --check
//
// One HostCallSpec per catalog function entry with a `rust_symbol` binding, in
// catalog order. Entries carrying `cfg_feature` are gated with the matching
// `#[cfg(feature = "...")]` attribute.

"""

PREAMBLE = """\
#[derive(Clone, Copy, Debug)]
pub struct HostCallSpec {
    pub name: &'static str,
    pub function: HostFunction,
}

pub const HOST_CALLS: &[HostCallSpec] = &[
"""

FOOTER = "];\n"


def catalog_path(root: Path) -> Path:
    return root / CATALOG


def host_call_entries(root: Path) -> list[tuple[str, str, str]]:
    """Return ``(name, rust_symbol, cfg_feature)`` in catalog order."""
    with catalog_path(root).open("rb") as handle:
        catalog = tomllib.load(handle)

    entries: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for entry in catalog.get("entry", []):
        symbol = str(entry.get("rust_symbol", ""))
        if not symbol:
            continue
        if str(entry.get("kind", "")) != "function":
            raise RuntimeError(
                f"catalog entry {entry.get('path')!r} carries a rust_symbol but is not a function"
            )
        name = str(entry.get("binding", ""))
        if not name.startswith(HOST_CALL_PREFIX):
            raise RuntimeError(
                f"host-call binding {name!r} must use the {HOST_CALL_PREFIX} prefix"
            )
        if not RUST_SYMBOL_RE.fullmatch(symbol):
            raise RuntimeError(f"host-call symbol {symbol!r} is not a Rust path")
        if name in seen:
            raise RuntimeError(f"duplicate host-call binding {name!r}")
        seen.add(name)
        entries.append((name, symbol, str(entry.get("cfg_feature", ""))))

    if not entries:
        raise RuntimeError(f"no host-call bindings found in {CATALOG}")
    return entries


def catalog_host_call_count(root: Path = ROOT) -> int:
    """Return how many ``HostCallSpec`` entries the catalog yields.

    Validators use this instead of a literal count so that adding a native
    function never requires editing a hand-maintained number.
    """
    return len(host_call_entries(root))


def render(root: Path) -> str:
    """Render the generated ``host_calls.rs`` body."""
    lines = [HEADER, PREAMBLE]
    for name, symbol, feature in host_call_entries(root):
        if feature:
            lines.append(f'    #[cfg(feature = "{feature}")]\n')
        lines.append(f'    HostCallSpec {{ name: "{name}", function: {symbol} }},\n')
    lines.append(FOOTER)
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail (non-zero) when the generated file is stale instead of writing it",
    )
    parser.add_argument("--output", default=OUTPUT, help="generated Rust file path")
    args = parser.parse_args()

    output = ROOT / args.output
    generated = render(ROOT)

    if args.check:
        # Byte comparison, not text: it also catches CRLF drift, since
        # Path.write_text() would otherwise translate \n to os.linesep on
        # Windows while the repository stores LF.
        current = output.read_bytes() if output.exists() else b""
        if current != generated.encode("utf-8"):
            print(
                f"R-3208 failure: {args.output} is stale; "
                f"run `python scripts/generate_host_calls.py` to regenerate it",
                file=sys.stderr,
            )
            return 1
        count = len(host_call_entries(ROOT))
        print(f"{args.output} matches the catalog ({count} host-call bindings)")
        return 0

    output.write_text(generated, encoding="utf-8", newline="")
    gated = sum(1 for _, _, feature in host_call_entries(ROOT) if feature)
    total = len(host_call_entries(ROOT))
    print(
        f"generated {total} host-call bindings at {args.output} "
        f"({total - gated} always on, {gated} feature-gated)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
