#!/usr/bin/env python3
"""Generate the mid-end host-call lowering tables from the typed STD catalog.

`midend/src/lowering_std_api.rs` and the six `lowering_std_host_*.rs` files used
to repeat, by hand, one descriptor per native function: the catalog binding, the
IR return type and the `returns_value` flag.  This generator removes that copy.
The catalog (``packages/spectra-contract/catalog/stdlib.toml``) is the single
source of truth for the descriptor *content*; the generator owns the
*presentation* (file split, arm order, section comments and the
helper-vs-literal rendering style) through the ``LAYOUT`` table below.

The migration followed the two steps required by R-3207:

1. ``--from-source`` re-derives the presentation from the hand-written tables
   that were on disk and asserts it equals ``LAYOUT``, so the embedded
   presentation data is provably the legacy tables' layout instead of a retyped
   approximation.
2. The default mode renders the descriptor content from the catalog.  Run
   against the pre-migration tree it reproduced every arm byte-for-byte - the
   generated header was the only addition - which is what ``--check`` keeps
   verifying.

``--check`` re-renders in memory and fails when a generated file is stale, which
is how the drift guard catches a hand edit of a generated file.

The ``numeric`` file is special: it holds no descriptor table, only the
``checked_f32`` conversion and the ``wrapping_*`` width dispatch, both derived
from the catalog entries of that namespace (the remaining ``std.numeric``
functions are lowered by the compiler builtin tables).

Coverage is enforced both ways.  A catalog function in a namespace the tables
own but absent from ``LAYOUT`` is placed automatically when its module occupies a
single group (appended in catalog order); when the module is split over several
groups or files the generator fails and asks for a placement instead of
guessing.  ``EXCLUDED`` names the catalog functions that other lowerings own, and
the generator fails when an exclusion goes stale.

Usage:
    python scripts/generate_lowering_tables.py
    python scripts/generate_lowering_tables.py --check
    python scripts/generate_lowering_tables.py --from-source
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
import tomllib
from dataclasses import dataclass, replace
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = "packages/spectra-contract/catalog/stdlib.toml"

# rustfmt defaults that decide how a descriptor arm is wrapped.
MAX_WIDTH = 100
FN_CALL_WIDTH = 60

# Rendering styles.  `helper` emits the short `host_*` constructors, `struct`
# emits the explicit `HostFunctionDescriptor` literal.
STYLE_HELPER = "helper"
STYLE_STRUCT = "struct"

SIMPLE_IR = {
    "int": "IRType::Int",
    "bool": "IRType::Bool",
    "string": "IRType::String",
    "float": "IRType::Float",
    "void": "IRType::Void",
    "unknown": "IRType::Unknown",
    "range": "IRType::Range",
}

# Helper constructor -> the IR return type (and `returns_value`) it produces.
HELPER_IR = {
    "host_int": ("int", True),
    "host_bool": ("bool", True),
    "host_string": ("string", True),
    "host_float": ("float", True),
    "host_void": ("void", False),
    "host_task_int": ("Task<int>", True),
    "host_task_bool": ("Task<bool>", True),
    "host_task_string": ("Task<string>", True),
    "host_tensor_dynamic": ("Tensor<float>", True),
    "host_tensor_rank0": ("Tensor<float,rank=0>", True),
}

# The helper a plain IR return type defaults to.  Types absent here (composite
# returns such as `Result<..>` or `Option<..>`) have no helper and default to the
# struct literal.
DEFAULT_HELPER = {
    "int": "host_int",
    "bool": "host_bool",
    "string": "host_string",
    "float": "host_float",
    "void": "host_void",
    "Task<int>": "host_task_int",
    "Task<bool>": "host_task_bool",
    "Task<string>": "host_task_string",
}

# Language-level names whose host symbol is not `spectra.std.<module>.<function>`.
# The runtime resolves `std.tensor.vector_f` through `full_f` (rank 1 fill) and
# `std.tensor.diff` through `backward`; the catalog keeps the language-level
# binding, so the alias lives here.
RUNTIME_ALIASES = {
    ("tensor", "vector_f"): "spectra.std.tensor.full_f",
    ("tensor", "matrix_f"): "spectra.std.tensor.full2_f",
    ("tensor", "diff"): "spectra.std.tensor.backward",
}

# Struct arms that reference the shared binding constant generated by
# `spectra-contract/build.rs` instead of repeating the literal string.  Every
# catalog function entry has such a constant, so the choice is presentation, not
# something the catalog can decide; the legacy tables used the constant for
# these entries only.
SHARED_BINDINGS = {
    "error": frozenset(
        {"new", "code", "message", "operation", "context", "origin", "retryable"}
    ),
    "collections": frozenset(
        {
            "list_new",
            "list_get",
            "list_get_option",
            "list_pop",
            "list_pop_front",
            "list_pop_option",
            "list_pop_front_option",
            "list_remove_at",
            "list_remove_at_option",
            "map_get",
            "map_get_option",
            "map_remove",
            "map_remove_option",
        }
    ),
    "fs": frozenset(
        {
            "fs_read",
            "fs_write",
            "fs_append",
            "fs_exists",
            "fs_remove",
            "create_dir_all",
            "remove_dir",
            "rename",
            "copy",
            "read_dir",
        }
    ),
    "env": frozenset(
        {"env_get", "env_get_option", "env_set", "env_args_count", "env_arg", "env_arg_option"}
    ),
}

MATCH_TAIL = (
    "        _ => None,",
    "    }",
    "}",
)

API_TAIL = MATCH_TAIL + (
    "",
    "/// Contract introspection: resolves the registered host-call name the",
    "/// `std.api.<module>.<function>` lowering would target, without exposing the",
    "/// internal descriptor type. Used by cross-crate contract drift tests.",
    "pub fn std_api_host_call_target(module: &str, function: &str) -> Option<&'static str> {",
    "    lookup_std_api_host_function(module, function).map(|d| d.runtime_name)",
    "}",
)

HEADER = """\
// @generated by scripts/generate_lowering_tables.py - do not edit manually.
//
// Source of truth: packages/spectra-contract/catalog/stdlib.toml
// Regenerate:      python scripts/generate_lowering_tables.py
// Verify:          python scripts/generate_lowering_tables.py --check
//
// {summary}
//
// Arm order, section comments and the helper-vs-literal rendering style are
// presentation data owned by the generator (see LAYOUT); runtime names, IR
// return types and `returns_value` come from the catalog.
"""

NUMERIC_PATH = "midend/src/lowering_std_host_numeric.rs"
NUMERIC_FUNCTION = "lookup_std_host_module_function"
# The numeric file owns direct host-call dispatch for checked scalar conversions,
# checked scalar arithmetic, and the `wrapping_*` width-specific functions.
WRAPPING_RE = re.compile(r"^wrapping_(add|sub|mul)_([iu])(8|16|32|64)$")
WRAPPING_OPS = ("add", "sub", "mul")
INT_WIDTHS = ("8", "16", "32", "64")

NUMERIC_SUMMARY = """\
`std.numeric` dispatcher: checked scalar conversions, checked scalar arithmetic,
// and the `wrapping_add`, `wrapping_sub` and `wrapping_mul` width table, all
// derived from the catalog entries of that namespace, followed by the
// hand-written group fallthrough."""

# Catalog functions in the namespaces the generated tables own that are lowered
# elsewhere (the compiler builtin tables and the JSON/ML/RAG host modules), so
# they must not appear in these tables.  `check_coverage` fails when a catalog
# entry is neither emitted nor listed here, which is what makes a forgotten
# native function loud instead of silently unlowered.
EXCLUDED = {
    "collections": frozenset({"iterator_from_values"}),
    "json": frozenset(
        {
            "decode_field",
            "decode_field_by_key",
            "encode_list",
            "encode_number",
            "encode_struct",
            "quote_char",
            "quote_string",
            "typed_error_field",
        }
    ),
    "ml": frozenset(
        {"generate", "onnx_run", "onnx_run_multi", "onnx_session_free", "onnx_session_from_bytes"}
    ),
    "tensor": frozenset(
        {
            "literal",
            "literal2",
            "literal2_f",
            "literal_f",
            "stats_device_pool_bytes_resident",
            "stats_device_pool_hits",
            "stats_device_pool_misses",
        }
    ),
}

@dataclass(frozen=True)
class Group:
    """A contiguous run of arms: one module, one optional legacy section banner."""

    module: str
    names: str
    comment: str | None = None


@dataclass(frozen=True)
class FileLayout:
    path: str
    function: str
    style: str
    summary: str
    groups: tuple[Group, ...]
    tail: tuple[str, ...] = MATCH_TAIL


# Presentation data: the arm layout of the legacy hand-written tables. The
# order, the section banners and the helper-vs-literal style of every arm live
# here. A catalog function whose module is not split over several groups is
# appended to its group automatically (see place_new_functions), so only a
# function of a shared module such as `collections` must be placed by hand.
# `--from-source` re-derives this table from the checked-in files and fails when
# the two drift apart.
LAYOUT: tuple[FileLayout, ...] = (
    FileLayout(
        path='midend/src/lowering_std_api.rs',
        function='lookup_std_api_host_function',
        style=STYLE_HELPER,
        summary="`std.api.*` host-call descriptors returned by `lookup_std_api_host_function`.",
        tail=API_TAIL,
        groups=(
            Group(
                module='http',
                names=(
                "method_name method_allows_body method_is_safe method_get method_head method_post "
                "method_put method_patch method_delete method_options status_reason status_class "
                "status_is_success status_continue status_switching_protocols status_ok status_created "
                "status_accepted status_no_content status_moved_permanently status_found "
                "status_not_modified status_bad_request status_unauthorized status_forbidden "
                "status_not_found status_method_not_allowed status_conflict status_unsupported_media_type "
                "status_unprocessable_content status_too_many_requests status_internal_server_error "
                "status_bad_gateway status_service_unavailable status_gateway_timeout "
                "header_name_is_valid header_value_is_valid request request_new request_method "
                "request_path request_body request_header request_with_header request_with_body "
                "request_cookie response response_new response_status response_header response_body_len "
                "header header_name header_value cookie cookie_name cookie_value cookie_with_options "
                "cookie_path cookie_domain cookie_max_age cookie_secure cookie_http_only cookie_same_site "
                "cookie_header response_with_cookie cookie_sign cookie_verify cookie_is_expired "
                "cookie_error_code cookie_error_message status"
                ),
            ),
            Group(
                module='json',
                names=(
                "validate kind parse value_kind value_len value_get value_at value_text value_number_bits "
                "value_bool value_free stringify"
                ),
            ),
            Group(
                module='jwt',
                names="sign verify",
            ),
            Group(
                module='oauth',
                names=(
                "client_new client_set_revocation_url authorization_url exchange_code refresh revoke "
                "token_access_token token_refresh_token token_type token_expires_at_ms token_scope"
                ),
            ),
            Group(
                module='tls',
                names="config_new config_mode client_config config_add_root",
            ),
            Group(
                module='errors',
                names=(
                "new internal_error status code message response exception_middleware last_code "
                "last_message"
                ),
            ),
            Group(
                module='security',
                names=(
                "csrf_policy csrf_allow_origin csrf_origin_count csrf_middleware ssrf_policy "
                "ssrf_allow_private_networks ssrf_allows"
                ),
            ),
            Group(
                module='session',
                names=(
                "memory_store redis_store store_kind create lookup id value created_at_ms expires_at_ms "
                "is_valid revoke error_code error_message"
                ),
            ),
            Group(
                module='websocket',
                names=(
                "client_new client_set_per_message_deflate client_set_max_message_bytes "
                "client_set_reconnect client_allow_private_networks client_connect server_new "
                "server_route server_listen server_local_port server_set_per_message_deflate "
                "server_set_max_message_bytes server_accept connection_peer_port connection_receive "
                "connection_send_text connection_send_binary_base64 connection_ping connection_close "
                "message_kind message_len message_text message_base64 message_release"
                ),
            ),
            Group(
                module='sse',
                names=(
                "server_new server_response server_listen server_local_port server_set_heartbeat_interval "
                "server_set_replay_capacity server_set_max_event_bytes server_accept server_publish "
                "event_new event_id event_type event_data event_retry_ms event_release "
                "connection_peer_port connection_last_event_id connection_send connection_heartbeat "
                "connection_close"
                ),
            ),
            Group(
                module='server',
                names=(
                "new listen serve state shutdown local_port signal stats set_max_body_bytes "
                "set_read_timeout set_idle_timeout set_tls_certificate tls_local_port"
                ),
            ),
            Group(
                module='client',
                names="new request timeout_ms set_ssrf_policy set_tls_config",
            ),
            Group(
                module='routing',
                names=(
                "router router_new route_count route_id route_add get post put patch delete route_match "
                "match_route_id match_param match_param_int last_conflict routes_export_openapi "
                "routes_set_request_schema"
                ),
            ),
            Group(
                module='query',
                names=(
                "type_string type_int type_bool parse len has count first value int bool schema "
                "schema_field bind binding_ok binding_error binding_count binding_value binding_int "
                "binding_bool error_code error_message"
                ),
            ),
            Group(
                module='form',
                names=(
                "type_string type_int type_bool parse len has count first value int bool schema "
                "schema_field bind binding_ok binding_error binding_count binding_value binding_int "
                "binding_bool error_code error_message"
                ),
            ),
            Group(
                module='multipart',
                names=(
                "parse part_count field_count file_count text part part_name part_filename "
                "part_content_type part_size part_is_file file_path file_read file_spool_to error_code "
                "error_message"
                ),
            ),
            Group(
                module='handler',
                names=(
                "text json bytes status with_header into_response into_text_response into_status_response "
                "error error_response error_code error_message last_error_message register_sync "
                "register_async register_sync_callback register_async_callback dispatch_sync "
                "dispatch_async"
                ),
            ),
            Group(
                module='middleware',
                names=(
                "chain chain_new chain_len register_sync register_sync_short_circuit register_async "
                "register_async_short_circuit register_logging logging_len logging_line "
                "logging_request_id register_rate_limit rate_limit_update register_api_key api_key_add "
                "api_key_revoke register_security_headers register_compression security_headers_configure "
                "security_headers_route use_sync use_async execute_sync execute_async last_trace "
                "trace_len trace_event trace_short_circuited"
                ),
            ),
            Group(
                module='validation',
                names=(
                "schema field min_length max_length range regex validate_json validate_form result_ok "
                "result_count result_field result_code result_message result_problem_json result_response "
                "error_code error_message"
                ),
            ),
            Group(
                module='trace',
                names=(
                "config_new config_set_sample_rate config_set_batch_size config_start config_shutdown "
                "span_start span_set_attribute span_set_attribute_int span_set_attribute_bool "
                "span_set_status span_end current parent inject extract flush last_error"
                ),
            ),
            Group(
                module='health',
                names="startup_complete startup_failed",
            ),
            Group(
                module='db.sqlite',
                names=(
                "open close prepare execute_async bind_null bind_int bind_float bind_text bind_blob step "
                "column_count column_type column_int column_float column_text reset finalize begin commit "
                "rollback last_error_code last_error_message"
                ),
            ),
            Group(
                module='db.postgres',
                names=(
                "open close prepare bind_null bind_int bind_float bind_text step column_count column_type "
                "column_int column_text reset finalize begin commit rollback execute_async step_async "
                "savepoint rollback_to release_savepoint copy_in_text_async copy_out_text_async listen "
                "notify_async notification_next_async notification_channel notification_payload "
                "notification_process_id notification_free notification_close last_error_code "
                "last_error_message"
                ),
            ),
            Group(
                module='db.redis',
                names=(
                "open open_async close close_async get get_async set set_async delete delete_async exists "
                "exists_async incr incr_async expire expire_async last_error_code last_error_message"
                ),
            ),
            Group(
                module='db.pool',
                names=(
                "sqlite_open postgres_open redis_open close with_connection postgres_with_connection "
                "redis_with_connection"
                ),
            ),
            Group(
                module='db.migrate',
                names="apply_sqlite status_sqlite",
            ),
            Group(
                module='cors',
                names=(
                "policy permissive allow_origin allow_method allow_header expose_header allow_credentials "
                "max_age middleware is_preflight preflight apply allowed_origin"
                ),
            ),
            Group(
                module='http3',
                names=(
                "server_config_new client_config_new handler_text server_start server_local_port "
                "server_shutdown client_connect client_shutdown client_request_new client_request_header "
                "client_request_open client_request_send_body client_request_send_trailers "
                "client_request_finish client_request_receive_response client_request_cancel "
                "response_status response_header response_trailer response_body_base64 response_body_len "
                "task_result task_cancel result_ok result_value result_error_code result_error_message "
                "handle_drop"
                ),
            ),
            Group(
                module='grpc',
                names=(
                "message_from_base64 message_to_base64 message_len message_free metadata_new "
                "metadata_insert metadata_append metadata_get metadata_len metadata_free status_new "
                "status_code status_message status_details_base64 status_set_details_base64 status_free "
                "response_message response_status response_metadata response_free error_code "
                "error_message error_details_base64 error_free client_connect client_connect_tls "
                "client_unary client_client_streaming client_server_streaming client_bidi_streaming "
                "stream_send stream_recv stream_finish stream_cancel stream_free server_bind "
                "server_bind_tls server_local_port server_shutdown server_free service_create "
                "service_handle_method service_free"
                ),
            ),
            Group(
                module='graphql',
                names=(
                "schema_new schema_set_workers schema_set_subscription_capacity schema_set_max_depth "
                "schema_set_max_complexity schema_set_introspection schema_field_json "
                "schema_field_callback schema_subscription_json schema_subscription_callback "
                "schema_finish schema_drop schema_sdl execute execute_named execute_http response_json "
                "response_status response_is_ok response_errors_json response_data_json response_drop "
                "subscribe subscription_next subscription_pending subscription_capacity "
                "subscription_is_cancelled subscription_cancel subscription_drop"
                ),
            ),
        ),
    ),
    FileLayout(
        path='midend/src/lowering_std_host_math_io_error.rs',
        function='lookup_std_host_group_math_io_error',
        style=STYLE_STRUCT,
        summary="`std.math`, `std.io`, `std.error` and the `std.collections` list descriptors.",
        groups=(
            Group(
                module='math',
                names=(
                "abs min max clamp sqrt_f pow_f floor_f ceil_f round_f sin_f cos_f tan_f log_f log2_f "
                "log10_f atan2_f pi e_const sign abs_f gcd lcm is_nan_f is_infinite_f"
                ),
            ),
            Group(
                module='io',
                names="print println eprint eprintln flush read_line input",
            ),
            Group(
                module='error',
                names="new code message operation context origin retryable",
            ),
            Group(
                module='collections',
                names=(
                "list_new list_push list_len list_get list_set list_contains list_clear list_free "
                "list_free_all"
                ),
            ),
        ),
    ),
    FileLayout(
        path='midend/src/lowering_std_host_collections_string.rs',
        function='lookup_std_host_group_collections_string',
        style=STYLE_STRUCT,
        summary="`std.collections` (map/stack/queue/set/iterator) and `std.string` descriptors.",
        groups=(
            Group(
                module='collections',
                names=(
                "map_new map_set map_get map_get_option map_contains map_remove map_remove_option map_len "
                "map_is_empty map_clear map_free map_free_all map_values_iter"
                ),
                comment='        // ── std.collections map ──────────────────────────────────────',
            ),
            Group(
                module='collections',
                names=(
                "set_new set_insert set_contains set_remove set_len set_get set_clear@host_void "
                "set_free@host_void list_iter set_iter map_iter iterator_next iterator_remaining "
                "iterator_free@host_void stack_new stack_push stack_pop stack_peek stack_len "
                "stack_is_empty stack_clear@host_void stack_free@host_void stack_free_all stack_iter "
                "queue_new queue_enqueue queue_dequeue queue_peek queue_len queue_is_empty "
                "queue_clear@host_void queue_free@host_void queue_free_all queue_iter"
                ),
                comment='        // ── std.collections set/iterator ──────────────────────────────',
            ),
            Group(
                module='string',
                names=(
                "len contains to_upper to_lower trim starts_with ends_with eq concat repeat_str char_at "
                "substring replace index_of split_first split_last is_empty count_occurrences reverse_str "
                "pad_left pad_right"
                ),
                comment='        // ── std.string ────────────────────────────────────────────────',
            ),
            Group(
                module='string',
                names="builder_new builder_push builder_len builder_finish builder_free split_by",
                comment='        // ── std.string string builder (R-3108) ────────────────────────',
            ),
            Group(
                module=None,
                names="",
                comment='        // ── std.convert ───────────────────────────────────────────────',
            ),
        ),
    ),
    FileLayout(
        path='midend/src/lowering_std_host_fs_env_result.rs',
        function='lookup_std_host_group_fs_env_result',
        style=STYLE_STRUCT,
        summary=(
            "`std.random`, the `std.collections` extras, `std.fs`, `std.env`, `std.option` and "
            "`std.result` descriptors."
            ),
        groups=(
            Group(
                module='random',
                names="random_seed random_int random_float random_bool",
            ),
            Group(
                module='collections',
                names=(
                "list_pop list_pop_front list_get_option list_pop_option list_pop_front_option "
                "list_insert_at list_remove_at list_remove_at_option list_index_of list_sort list_map "
                "list_filter list_reduce list_sort_by"
                ),
                comment='        // ── std.collections extras ────────────────────────────────────',
            ),
            Group(
                module='fs',
                names=(
                "fs_read fs_write fs_append fs_exists fs_remove create_dir_all remove_dir rename copy "
                "read_dir"
                ),
                comment='        // ── std.fs ────────────────────────────────────────────────────',
            ),
            Group(
                module='env',
                names="env_get env_get_option env_set env_args_count env_arg env_arg_option",
                comment='        // ── std.env ───────────────────────────────────────────────────',
            ),
            Group(
                module='option',
                names="is_some is_none option_unwrap option_unwrap_or option_map",
                comment='        // ── std.option ────────────────────────────────────────────────',
            ),
            Group(
                module='result',
                names="is_ok is_err result_unwrap result_unwrap_or result_unwrap_err result_map result_map_err",
                comment='        // ── std.result ────────────────────────────────────────────────',
            ),
        ),
    ),
    FileLayout(
        path='midend/src/lowering_std_host_convert_time.rs',
        function='lookup_std_host_group_convert_time',
        style=STYLE_STRUCT,
        summary="`std.convert`, `std.char`, `std.range` and `std.time` descriptors.",
        groups=(
            Group(
                module='convert',
                names=(
                "int_to_string float_to_string bool_to_string string_to_int string_to_float int_to_float "
                "float_to_int string_to_int_or string_to_float_or string_to_bool bool_to_int"
                ),
            ),
            Group(
                module='char',
                names=(
                "is_alpha is_digit_char is_whitespace_char is_upper_char is_lower_char to_upper_char "
                "to_lower_char is_alphanumeric"
                ),
                comment='        // ── std.char ──────────────────────────────────────────────────',
            ),
            Group(
                module='range',
                names="create len@host_int at@host_int eq start@host_int end@host_int is_inclusive iter",
                comment='        // ── std.range ─────────────────────────────────────────────────',
            ),
            Group(
                module='time',
                names=(
                "time_now_millis time_now_secs sleep_ms monotonic_millis monotonic_nanos duration_ms "
                "duration_secs duration_millis duration_secs_value duration_add duration_sub instant_now "
                "instant_elapsed_ms instant_add instant_has_elapsed sleep unix_to_utc utc_year utc_month "
                "utc_day utc_hour utc_minute utc_second"
                ),
                comment='        // ── std.time ──────────────────────────────────────────────────',
            ),
            Group(
                module=None,
                names="",
                comment='        // ── std.random ────────────────────────────────────────────────',
            ),
        ),
    ),
    FileLayout(
        path='midend/src/lowering_std_host_tensor_ml.rs',
        function='lookup_std_host_group_tensor_ml',
        style=STYLE_HELPER,
        summary="`std.tensor`, `std.ml`, `std.concurrent` and `std.serve` descriptors.",
        groups=(
            Group(
                module='tensor',
                names=(
                "vector_f matrix_f zeros ones full full_f arange zeros2 ones2 full2 full2_f len rank dim "
                "rows cols is_valid@struct get get_f set set_f get2 get2_f set2 set2_f reshape flatten "
                "permute slice concat stack add sub mul@host_tensor_dynamic div sum sum_f "
                "sum_t@host_tensor_rank0 mean_f mean_t max min argmax matmul matmul_batched transpose dot "
                "dot_t neg exp_f log_f sqrt_f relu sigmoid_f tanh_f seed uniform uniform_f normal_f "
                "bernoulli categorical set_deterministic_mode deterministic_mode tolerance_abs "
                "tolerance_rel device device_available@struct device_status storage_device to_device cpu sync precision "
                "to_precision stats_allocations stats_active stats_peak_bytes stats_reused_buffers "
                "stats_pool_hits stats_pool_misses stats_active_bytes stats_scratch_reuses "
                "kernel_strategy stats_kernel_ops stats_kernel_elements stats_device_transfers "
                "stats_gpu_kernel_ops stats_gpu_errors stats_cpu_fallbacks stats_device_resident_tensors "
                "stats_gpu_backward_ops stats_graph_nodes stats_lifetime_records stats_released_lifetimes "
                "stats_allocation_sites stats_reuse_rate_per_mille memory_report reset_stats "
                "requires_grad@host_tensor_dynamic diff backward grad@host_tensor_dynamic zero_grad "
                "set_grad_enabled grad_enabled@struct free free_all refill"
                ),
            ),
            Group(
                module='ml',
                names=(
                "module_new module_add_parameter module_parameter_count module_parameter "
                "module_set_training module_is_training@struct linear conv2d dropout max_pool2d mse_loss "
                "bce_loss cross_entropy_loss nll_loss sgd_step sgd_momentum_step adam_step adamw_step "
                "exp_lr unscale_grad dataset_from_tensors dataset_from_csv dataset_from_jsonl "
                "dataset_from_npy dataset_from_directory dataset_len dataset_map_features "
                "dataset_filter_label_min dataset_train_split dataset_test_split dataloader_new "
                "dataloader_batch_count dataloader_batch_features dataloader_batch_labels "
                "dataframe_from_csv dataframe_rows dataframe_cols dataframe_column experiment_start "
                "experiment_set_config experiment_log_metric experiment_log_artifact "
                "experiment_set_lockfile experiment_set_model_output experiment_finish "
                "experiment_manifest_path experiment_repro_command experiment_compare_manifests "
                "distributed_session_start distributed_worker_step distributed_global_step "
                "distributed_worker_step_count distributed_checkpoint_save distributed_resume "
                "distributed_summary distributed_train_multithread distributed_train_tcp "
                "distributed_train_dataset_multithread distributed_train_dataset_tcp onnx_export_weights "
                "onnx_import_summary onnx_validate onnx_roundtrip embedding_lookup positional_encoding "
                "layer_norm gelu swiglu attention kv_cache_new kv_cache_append kv_cache_keys "
                "kv_cache_values kv_cache_len logits_sample logits_sample_seeded generate_ex "
                "tokenizer_wordpiece tokenizer_load tokenizer_encode tokenizer_decode train_bpe "
                "train_wordpiece tokenizer_vocab text_embed_model_session text_embed_model embedding_load "
                "vector_index_new vector_index_insert vector_index_query vector_index_persist "
                "vector_index_load vector_index_set_metadata@struct vector_index_metrics rag_chunk_text "
                "rag_build_prompt rag_evaluate_answer metrics_classification metrics_regression "
                "metrics_ranking metrics_generation serving_metrics evaluation_report artifact_new "
                "artifact_set_metadata@struct artifact_add_tensor@struct artifact_save@struct "
                "artifact_load artifact_tensor artifact_metadata artifact_validate@struct artifact_free"
                ),
                comment='        // ── std.ml ───────────────────────────────────────────────────',
            ),
            Group(
                module='concurrent',
                names=(
                "task_join task_spawn_fn task_spawn_batch task_join_batch_sum task_is_done@struct "
                "channel_new channel_send@struct channel_recv channel_len channel_close counter_new "
                "counter_add counter_get pipeline_sum stats_tasks_spawned stats_channels reset"
                ),
                comment='        // ── std.concurrent ───────────────────────────────────────────',
            ),
            Group(
                module='serve',
                names=(
                "server_new server_warmup@struct server_is_warm@struct server_enqueue "
                "server_cancel@struct server_process_batch server_result server_pending "
                "server_set_timeout@struct server_resident_model server_benchmark "
                "server_set_input_policy@struct server_set_output_policy@struct "
                "server_set_rate_limit@struct server_set_fallback@struct server_last_diagnostic "
                "server_audit_log server_set_model_version@struct server_monitoring_snapshot "
                "server_distribution_summary drift_check export_monitoring server_register_model_linear "
                "server_register_named_model_linear server_register_model_onnx "
                "server_register_named_model_onnx server_infer server_result_vector http_start "
                "http_stop@struct reset"
                ),
                comment='        // ── std.serve ────────────────────────────────────────────────',
            ),
        ),
    ),
)


@dataclass(frozen=True)
class Entry:
    module: str
    function: str
    binding: str
    returns_value: bool
    ir_return: str


def catalog_path(root: Path) -> Path:
    return root / CATALOG


def load_catalog(root: Path = ROOT) -> dict[tuple[str, str], Entry]:
    """Index the catalog function entries by ``(module, function)``."""
    with catalog_path(root).open("rb") as handle:
        catalog = tomllib.load(handle)

    entries: dict[tuple[str, str], Entry] = {}
    for raw in catalog.get("entry", []):
        if str(raw.get("kind", "")) != "function":
            continue
        path = str(raw["path"])
        parts = path.split(".")
        module = ".".join(parts[2:-1]) if parts[1] == "api" else ".".join(parts[1:-1])
        key = (module, parts[-1])
        if key in entries:
            raise RuntimeError(f"duplicate catalog function {path!r}")
        entries[key] = Entry(
            module=module,
            function=parts[-1],
            binding=str(raw["binding"]),
            returns_value=bool(raw["returns_value"]),
            ir_return=str(raw["ir_return"]),
        )
    return entries


def binding_const_name(entry: Entry) -> str:
    """`std.fs.fs_read` -> `STD_FS_FS_READ_BINDING` (see contract build.rs)."""
    path = f"std.{entry.module}.{entry.function}"
    name = "".join(ch.upper() if ch.isalnum() else "_" for ch in path)
    return f"{name}_BINDING"


def render_ir(ir_return: str, indent: int) -> list[str]:
    """Render a catalog `ir_return` as the Rust `IRType` expression lines."""
    pad = " " * indent
    if ir_return in SIMPLE_IR:
        return [pad + SIMPLE_IR[ir_return]]
    if ir_return == "Error":
        return [pad + "builtin_error_ir_type()"]
    if ir_return.startswith("Result<") and ir_return.endswith(">"):
        inner = render_ir(ir_return[len("Result<") : -1], indent)
        return wrap_call("builtin_result_ir_type", inner)
    if ir_return == "Option<string>":
        return [
            pad + "IRType::Enum {",
            pad + '    name: "Option_string".to_string(),',
            pad + "    variants: vec![",
            pad + '        ("Some".to_string(), Some(vec![IRType::String])),',
            pad + '        ("None".to_string(), None),',
            pad + "    ],",
            pad + "}",
        ]
    if re.fullmatch(r"(List|Map|Set|Iterator|Stack|Queue)<.*>", ir_return):
        name = re.sub(r"[<>,]", "_", ir_return).rstrip("_")
        return [
            pad + "IRType::Struct {",
            pad + f'    name: "{name}".to_string(),',
            pad + "    fields: Vec::new(),",
            pad + "}",
        ]
    match = re.fullmatch(r"Tensor<([a-z0-9]+)(?:,rank=(\d+))?>", ir_return)
    if match:
        dtype = {"float": "IRType::Float", "int": "IRType::Int"}[match.group(1)]
        rank = match.group(2)
        return [
            pad + "IRType::Tensor {",
            pad + f"    dtype: Box::new({dtype}),",
            pad + f"    rank: {f'Some({rank})' if rank else 'None'},",
            pad + "    dims: None,",
            pad + "    layout: None,",
            pad + "    device: None,",
            pad + "}",
        ]
    raise RuntimeError(f"no IRType rendering for catalog ir_return {ir_return!r}")


def wrap_call(function: str, inner: list[str]) -> list[str]:
    """`call(` + the expression's first line, closing on the expression's last."""
    first = inner[0].lstrip()
    if len(inner) == 1:
        return [inner[0][: len(inner[0]) - len(first)] + f"{function}({first})"]
    return [inner[0][: len(inner[0]) - len(first)] + f"{function}({first}", *inner[1:-1], inner[-1] + ")"]


def runtime_expression(entry: Entry, style: str) -> str:
    alias = RUNTIME_ALIASES.get((entry.module, entry.function))
    if alias is not None:
        return f'"{alias}"'
    if style == STYLE_STRUCT and entry.function in SHARED_BINDINGS.get(entry.module, ()):
        return f"spectra_contract::{binding_const_name(entry)}"
    return f'"{entry.binding}"'


def arm_style(
    layout: FileLayout, catalog: dict[tuple[str, str], Entry], module: str, function: str
) -> str:
    """The rendering style LAYOUT prescribes for one arm."""
    for group in layout.groups:
        if group.module != module:
            continue
        for item in group.names.split():
            if item.split("@", 1)[0] != function:
                continue
            if "@" in item:
                return item.split("@", 1)[1]
            entry = catalog.get((module, function))
            if entry is None:
                raise RuntimeError(f"{layout.path}: no catalog entry for {module}.{function}")
            return default_style(layout.style, entry)
    raise RuntimeError(f"{layout.path}: {module}.{function} is not in the layout")


def default_style(style: str, entry: Entry) -> str:
    if style == STYLE_STRUCT:
        return STYLE_STRUCT
    return DEFAULT_HELPER.get(entry.ir_return, STYLE_STRUCT)


def emit_arm(entry: Entry, style: str, indent: str = "        ") -> list[str]:
    """Render one match arm, byte-identical to the legacy hand-written text."""
    runtime = runtime_expression(entry, style)
    head = f'{indent}("{entry.module}", "{entry.function}")'
    if style != STYLE_STRUCT:
        ir_return, returns_value = HELPER_IR[style]
        if ir_return != entry.ir_return or returns_value != entry.returns_value:
            raise RuntimeError(
                f"{entry.module}.{entry.function}: {style} returns {ir_return}/"
                f"{returns_value} but the catalog says {entry.ir_return}/"
                f"{entry.returns_value}; update LAYOUT or the catalog"
            )
        single = f'{head} => Some({style}({runtime})),'
        if len(single) <= MAX_WIDTH:
            return [single]
        body = f"Some({style}({runtime}))"
        call_arg = f"{style}({runtime})"
        if len(f"            {body}") <= MAX_WIDTH and len(call_arg) <= FN_CALL_WIDTH:
            return [f"{head} => {{", f"            {body}", f"{indent}}}"]
        return [f"{head} => Some({style}(", f'            "{entry.binding}",' if runtime == f'"{entry.binding}"' else f"            {runtime},", f"{indent})),"]

    type_lines = render_ir(entry.ir_return, 12)
    if len(type_lines) == 1:
        type_block = [f"            return_type: {type_lines[0].strip()},"]
    else:
        type_block = [f"            return_type: {type_lines[0].strip()}"]
        type_block += type_lines[1:-1]
        type_block.append(type_lines[-1] + ",")
    return [
        f"{head} => Some(HostFunctionDescriptor {{",
        f"            runtime_name: {runtime},",
        *type_block,
        f"            returns_value: {str(entry.returns_value).lower()},",
        f"{indent}}}),",
    ]


def render_file(layout: FileLayout, catalog: dict[tuple[str, str], Entry]) -> str:
    lines = [HEADER.format(summary=layout.summary)]
    lines += [
        "use super::*;",
        "",
        f"pub(crate) fn {layout.function}(",
        "    module: &str,",
        "    function: &str,",
        ") -> Option<HostFunctionDescriptor> {",
        "    match (module, function) {",
    ]
    for group in layout.groups:
        if group.comment is not None:
            lines.append(group.comment)
        for item in group.names.split():
            function = item.split("@", 1)[0]
            entry = catalog.get((group.module, function))
            if entry is None:
                raise RuntimeError(f"{layout.path}: no catalog entry for {group.module}.{function}")
            lines += emit_arm(entry, arm_style(layout, catalog, group.module, function))
    lines += layout.tail
    return "\n".join(lines) + "\n"


def numeric_wrapping(catalog: dict[tuple[str, str], Entry]) -> list[tuple[bool, str, list[str]]]:
    """`(signed, width, function names)` groups in dispatch order."""
    groups: dict[tuple[bool, str], dict[str, str]] = {}
    for (module, function), entry in catalog.items():
        if module != "numeric":
            continue
        match = WRAPPING_RE.fullmatch(function)
        if match is None:
            continue
        op, prefix, width = match.groups()
        if entry.ir_return != f"ExactInt<{prefix}{width}>":
            raise RuntimeError(
                f"numeric.{function}: catalog ir_return {entry.ir_return!r} does not match "
                f"the wrapping width {prefix}{width}"
            )
        groups.setdefault((prefix == "i", width), {})[op] = function
    if not groups:
        raise RuntimeError("the catalog has no std.numeric wrapping_* entries")
    ordered = []
    for signed in (True, False):
        for width in INT_WIDTHS:
            ops = groups.get((signed, width))
            if ops is None:
                continue
            missing = [op for op in WRAPPING_OPS if op not in ops]
            if missing:
                raise RuntimeError(f"numeric wrapping_{{{','.join(missing)}}}_{width} is missing")
            ordered.append((signed, width, [ops[op] for op in WRAPPING_OPS]))
    return ordered


def render_numeric(catalog: dict[tuple[str, str], Entry]) -> str:
    lines = [HEADER.format(summary=NUMERIC_SUMMARY)]
    lines += [
        "use super::*;",
        "",
        f"pub(crate) fn {NUMERIC_FUNCTION}(",
        "    module: &str,",
        "    function: &str,",
        ") -> Option<HostFunctionDescriptor> {",
        '    if module == "numeric" {',
    ]
    conversions = sorted(
        (entry for (module, _), entry in catalog.items() if module == "numeric" and entry.ir_return.startswith("ExactFloat<")),
        key=lambda e: e.function,
    )
    for entry in conversions:
        width = entry.ir_return[len("ExactFloat<") : -1].upper()
        lines += [
            f'        if function == "{entry.function}" {{',
            "            return Some(HostFunctionDescriptor {",
            f'                runtime_name: "{entry.binding}",',
            "                return_type: IRType::ExactFloat {",
            f"                    width: IRFloatWidth::{width},",
            "                },",
            f"                returns_value: {str(entry.returns_value).lower()},",
            "            });",
            "        }",
        ]
    checked_ints = sorted(
        (
            entry
            for (module, _), entry in catalog.items()
            if module == "numeric"
            and entry.function.startswith("checked_")
            and entry.ir_return.startswith("ExactInt<")
        ),
        key=lambda e: e.function,
    )
    for entry in checked_ints:
        width_text = entry.ir_return[len("ExactInt<") : -1]
        if not width_text or width_text[0] not in "iu" or width_text[1:] not in INT_WIDTHS:
            raise RuntimeError(
                f"numeric checked function has unsupported exact integer return: "
                f"{entry.function} -> {entry.ir_return}"
            )
        signed = width_text[0] == "i"
        width = width_text[1:]
        lines += [
            f'        if function == "{entry.function}" {{',
            "            return Some(HostFunctionDescriptor {",
            f'                runtime_name: "{entry.binding}",',
            "                return_type: IRType::ExactInt {",
            f"                    signed: {str(signed).lower()},",
            f"                    width: IRIntWidth::I{width},",
            "                },",
            f"                returns_value: {str(entry.returns_value).lower()},",
            "            });",
            "        }",
        ]
    lines += [
        "        let (signed, width): (bool, IRIntWidth) = match function {",
    ]
    for signed, width, functions in numeric_wrapping(catalog):
        pattern = " | ".join(f'"{name}"' for name in functions)
        # `IntWidth` only has signed variants; the unsigned widths are the same
        # enum values paired with `signed = false`.
        single = f"            {pattern} => ({str(signed).lower()}, IRIntWidth::I{width}),"
        if len(single) <= MAX_WIDTH:
            lines.append(single)
        else:
            lines += [
                f"            {pattern} => {{",
                f"                ({str(signed).lower()}, IRIntWidth::I{width})",
                "            }",
            ]
    lines += [
        "            _ => return None,",
        "        };",
        "        return Some(HostFunctionDescriptor {",
        '            runtime_name: Box::leak(format!("spectra.std.numeric.{function}").into_boxed_str()),',
        "            return_type: IRType::ExactInt { signed, width },",
        "            returns_value: true,",
        "        });",
        "    }",
        "    lookup_std_host_group_math_io_error(module, function)",
        "        .or_else(|| lookup_std_host_group_tensor_ml(module, function))",
        "        .or_else(|| lookup_std_host_group_collections_string(module, function))",
        "        .or_else(|| lookup_std_host_group_convert_time(module, function))",
        "        .or_else(|| lookup_std_host_group_fs_env_result(module, function))",
        "}",
    ]
    return "\n".join(lines) + "\n"


def place_new_functions(catalog: dict[tuple[str, str], Entry]) -> tuple[FileLayout, ...]:
    """`LAYOUT` plus catalog functions that are not listed anywhere yet.

    A catalog function whose module occupies exactly one group across every
    generated file is appended to that group in catalog order, so adding a native
    function to an existing namespace needs no hand edit.  A function in a module
    that is split over several groups or files (``std.collections`` is shared by
    three files) is left for :func:`check_coverage` to report rather than placed
    on a guess.
    """
    slots: dict[str, list[tuple[int, int]]] = {}
    listed: dict[str, set[str]] = {}
    for layout_index, layout in enumerate(LAYOUT):
        for group_index, group in enumerate(layout.groups):
            if group.module is None:
                continue
            slots.setdefault(group.module, []).append((layout_index, group_index))
            listed.setdefault(group.module, set()).update(
                item.split("@", 1)[0] for item in group.names.split()
            )

    additions: dict[tuple[int, int], list[str]] = {}
    for (module, function), _ in catalog.items():
        if module not in slots or function in EXCLUDED.get(module, ()):
            continue
        if function in listed[module]:
            continue
        if len(slots[module]) == 1:
            additions.setdefault(slots[module][0], []).append(function)

    placed = []
    for layout_index, layout in enumerate(LAYOUT):
        groups = []
        for group_index, group in enumerate(layout.groups):
            extra = additions.get((layout_index, group_index), [])
            names = " ".join(filter(None, [group.names, " ".join(extra)]))
            groups.append(Group(group.module, names, group.comment))
        placed.append(replace(layout, groups=tuple(groups)))
    return tuple(placed)


def check_coverage(
    catalog: dict[tuple[str, str], Entry], layouts: tuple[FileLayout, ...]
) -> list[str]:
    """Every catalog function in an owned namespace must be emitted or excluded."""
    problems: list[str] = []
    slots: dict[str, int] = {}
    emitted: dict[str, set[str]] = {}
    for layout in layouts:
        for group in layout.groups:
            if group.module is None:
                continue
            slots[group.module] = slots.get(group.module, 0) + 1
            emitted.setdefault(group.module, set()).update(
                item.split("@", 1)[0] for item in group.names.split()
            )

    for module in sorted(emitted):
        entries = {function for (entry_module, function) in catalog if entry_module == module}
        excluded = EXCLUDED.get(module, frozenset())
        missing = sorted(entries - emitted[module] - excluded)
        if missing:
            problems.append(
                f"{module}: catalog functions missing from LAYOUT: {missing} "
                f"(the module is spread over {slots[module]} groups; place them by hand)"
            )
        stale = sorted(excluded - entries)
        if stale:
            problems.append(f"{module}: EXCLUDED lists unknown catalog functions: {stale}")
        both = sorted(emitted[module] & excluded)
        if both:
            problems.append(f"{module}: functions are both emitted and excluded: {both}")

    numeric = {function for (module, function) in catalog if module == "numeric"}
    selected = {
        function
        for function in numeric
        if WRAPPING_RE.fullmatch(function)
        or catalog[("numeric", function)].ir_return.startswith("ExactFloat<")
        or catalog[("numeric", function)].ir_return.startswith("ExactInt<")
    }
    unowned = sorted(numeric - selected)
    if unowned:
        problems.append(f"numeric: catalog functions that no lowering owns: {unowned}")
    return problems


def prepare(root: Path = ROOT) -> tuple[dict[tuple[str, str], Entry], tuple[FileLayout, ...]]:
    """Load the catalog, place new functions and fail on coverage gaps."""
    catalog = load_catalog(root)
    layouts = place_new_functions(catalog)
    problems = check_coverage(catalog, layouts)
    if problems:
        raise RuntimeError(
            "the lowering tables do not cover the catalog:\n  " + "\n  ".join(problems)
        )
    return catalog, layouts


def render_all(root: Path = ROOT) -> dict[str, str]:
    catalog, layouts = prepare(root)
    rendered = {layout.path: render_file(layout, catalog) for layout in layouts}
    rendered[NUMERIC_PATH] = render_numeric(catalog)
    return rendered


def auto_placed_names(layouts: tuple[FileLayout, ...]) -> list[str]:
    """Catalog functions the generator placed in a group on its own."""
    placed: list[str] = []
    for layout, base in zip(layouts, LAYOUT):
        listed = {
            item.split("@", 1)[0] for group in base.groups for item in group.names.split()
        }
        for group in layout.groups:
            for item in group.names.split():
                name = item.split("@", 1)[0]
                if name not in listed:
                    placed.append(f"{group.module}.{name}")
    return placed


def arm_count(layouts: tuple[FileLayout, ...]) -> int:
    return sum(len(group.names.split()) for layout in layouts for group in layout.groups)


def extract_layout(
    path: Path,
) -> tuple[str, tuple[tuple[str | None, str, str | None], ...], str]:
    """Re-derive a table file's arm layout (order, banners, styles) from its text.

    This is the step-1 half of the migration: the descriptor content of an arm is
    irrelevant here, only the order, the section banners and the rendering style,
    which is what ``LAYOUT`` records.
    """
    lines = path.read_text(encoding="utf-8").split("\n")
    function = next(
        line.split("fn ", 1)[1].split("(", 1)[0]
        for line in lines
        if line.startswith("pub(crate) fn ")
    )
    start = next(i for i, line in enumerate(lines) if line.strip() == "match (module, function) {")
    end = next(i for i, line in enumerate(lines) if i > start and line.strip() == "_ => None,")

    groups: list[tuple[str | None, list[tuple[str, str]], str | None]] = []
    banner: str | None = None
    index = start + 1
    while index < end:
        stripped = lines[index].strip()
        if stripped.startswith("//"):
            banner = f"{banner}\n{lines[index]}" if banner else lines[index]
            index += 1
            continue
        head = re.match(r'\("([\w.]+)", "(\w+)"\)', stripped)
        if head is None:
            index += 1
            continue
        module, name = head.groups()
        block = [lines[index]]
        depth = sum(lines[index].count(ch) for ch in "({") - sum(
            lines[index].count(ch) for ch in ")}"
        )
        while depth > 0:
            index += 1
            block.append(lines[index])
            depth += sum(lines[index].count(ch) for ch in "({") - sum(
                lines[index].count(ch) for ch in ")}"
            )
        index += 1
        text = "\n".join(block)
        if "HostFunctionDescriptor {" in text:
            style = STYLE_STRUCT
        else:
            helper = re.search(r"Some\((host_\w+)\(", text)
            if helper is None:
                raise RuntimeError(f"{path}: cannot classify the arm for {module}.{name}")
            style = helper.group(1)
        if not groups or groups[-1][0] != module or banner is not None:
            groups.append((module, [], banner))
            banner = None
        groups[-1][1].append((name, style))
    if banner is not None:
        groups.append((None, [], banner))

    # The file-level style is the majority rendering; every arm that deviates
    # carries an explicit `@<style>` marker in LAYOUT.
    styles = [STYLE_STRUCT if style == STYLE_STRUCT else STYLE_HELPER for _, names, _ in groups for _, style in names]
    majority = STYLE_HELPER if styles.count(STYLE_HELPER) >= styles.count(STYLE_STRUCT) else STYLE_STRUCT
    return function, tuple((module, tuple(names), banner) for module, names, banner in groups), majority


def check_from_source(root: Path = ROOT) -> list[str]:
    """Step 1 proof: the embedded LAYOUT equals the checked-in tables' layout.

    The on-disk order, section banners and per-arm rendering style are re-derived
    from the file text and compared with ``LAYOUT``; the expected style of an arm
    is the one the generator would emit for it.
    """
    catalog, layouts = prepare(root)
    problems: list[str] = []
    for layout in layouts:
        path = root / layout.path
        if not path.exists():
            problems.append(f"{layout.path}: missing")
            continue
        function, groups, majority = extract_layout(path)
        if function != layout.function:
            problems.append(f"{layout.path}: function {function} != {layout.function}")
        if majority != layout.style:
            problems.append(f"{layout.path}: file style {majority} != {layout.style}")
        expected = tuple(
            (group.module, tuple(item.split("@", 1)[0] for item in group.names.split()), group.comment)
            for group in layout.groups
        )
        observed = tuple((module, tuple(name for name, _ in names), banner) for module, names, banner in groups)
        if observed != expected:
            for index, (got, want) in enumerate(zip(observed, expected)):
                if got != want:
                    problems.append(
                        f"{layout.path}: group {index} differs\n  on disk: {got}\n  LAYOUT:  {want}"
                    )
                    break
            else:
                problems.append(f"{layout.path}: group count {len(observed)} != {len(expected)}")
            continue
        for module, names, _ in groups:
            if module is None:
                continue
            for name, style in names:
                if style != arm_style(layout, catalog, module, name):
                    problems.append(
                        f"{layout.path}: {module}.{name} renders as {style}, "
                        f"LAYOUT says {arm_style(layout, catalog, module, name)}"
                    )
    return problems


def stale(rendered: dict[str, str], root: Path = ROOT) -> list[str]:
    report = []
    for relative, text in rendered.items():
        path = root / relative
        if not path.exists():
            report.append(f"{relative} is missing; run `python scripts/generate_lowering_tables.py`")
            continue
        raw = path.read_bytes()
        if b"\r\n" in raw:
            report.append(
                f"{relative} uses CRLF line endings; run "
                f"`python scripts/generate_lowering_tables.py` (the generator writes LF)"
            )
            continue
        current = raw.decode("utf-8")
        if current == text:
            continue
        diff = list(
            difflib.unified_diff(
                current.splitlines(),
                text.splitlines(),
                fromfile=f"{relative} (on disk)",
                tofile=f"{relative} (generated)",
                lineterm="",
                n=1,
            )
        )
        hint = "\n".join(diff[:24]) or f"{relative}: file is empty"
        report.append(
            f"{relative} is stale; run `python scripts/generate_lowering_tables.py`:\n{hint}"
        )
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail (non-zero) when a generated file is stale instead of writing it",
    )
    parser.add_argument(
        "--from-source",
        action="store_true",
        help="re-derive the layout from the checked-in files and compare it with LAYOUT",
    )
    args = parser.parse_args()

    if args.from_source:
        problems = check_from_source(ROOT)
        if problems:
            print(
                "R-3207 failure: the checked-in tables drifted from the catalog layout:",
                file=sys.stderr,
            )
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            return 1
        _, layouts = prepare(ROOT)
        print(
            f"the checked-in tables match LAYOUT "
            f"({arm_count(layouts)} arms across {len(LAYOUT)} files)"
        )
        return 0

    rendered = render_all(ROOT)
    _, layouts = prepare(ROOT)
    placed = auto_placed_names(layouts)
    for name in placed:
        print(f"placed new catalog function {name} at the end of its group")
    if args.check:
        report = stale(rendered, ROOT)
        if report:
            for entry in report:
                print(f"R-3207 failure: {entry}", file=sys.stderr)
            return 1
        print(f"the lowering tables match the catalog ({arm_count(layouts)} generated arms)")
        return 0

    for relative, text in rendered.items():
        # `newline=""` keeps the generated files LF, like every other Rust source
        # in the repository, regardless of the host platform.
        (ROOT / relative).write_text(text, encoding="utf-8", newline="")
    print(
        f"generated {arm_count(layouts)} arms across {len(rendered)} lowering tables"
        f" ({len(placed)} placed from the catalog)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
