#!/usr/bin/env python3
"""Validate the generated `spectra-api` host-call table (R-3208).

Checks:
* the generator reports the checked-in table as current (`--check`),
* the generated file carries its do-not-edit header, keeps the `HostCallSpec`
  struct, and matches the catalog's entry count and cfg-gating,
* `api_tests.rs` derives the host-call count from `HOST_CALLS.len()` and no
  literal `557`/`529` count survives anywhere in the crate sources,
* `cargo test -p spectra-api` passes.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import generate_host_calls  # noqa: E402

GENERATED = "packages/spectra-api/src/host_calls.rs"
API_TESTS = "packages/spectra-api/src/api_tests.rs"
HEADER_MARKER = "// @generated by scripts/generate_host_calls.py - do not edit manually."
STALE_COUNT_RE = re.compile(r"HOST_CALLS\.len\(\)\s*,\s*(?:557|529)\b")
DERIVED_ASSERT = "assert_eq!(spectra_api_host_call_count(), HOST_CALLS.len())"


def cargo_command() -> str:
    cargo = "cargo.exe" if sys.platform.startswith("win") else "cargo"
    home = Path(os.environ.get("USERPROFILE") or os.environ.get("HOME") or "")
    candidate = home / ".cargo" / "bin" / cargo
    return str(candidate) if candidate.exists() else "cargo"


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def fail(message: str) -> None:
    print(f"R-3208 validation failed: {message}", file=sys.stderr)
    raise SystemExit(1)


def require(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def run_command(args: list[str]) -> None:
    completed = subprocess.run(
        args,
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if completed.returncode != 0:
        fail(f"command {' '.join(args)} failed:\n{completed.stdout}")


def validate_generator() -> None:
    completed = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "generate_host_calls.py"), "--check"],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    require(
        completed.returncode == 0,
        f"generate_host_calls.py --check reported a stale table:\n{completed.stdout}",
    )


def validate_generated_file() -> None:
    generated_bytes = (ROOT / GENERATED).read_bytes()
    require(
        b"\r\n" not in generated_bytes,
        f"{GENERATED} must use LF line endings like the rest of the repository",
    )
    generated = generated_bytes.decode("utf-8")
    require(HEADER_MARKER in generated, "generated table must carry the do-not-edit header")
    for term in [
        "pub struct HostCallSpec {",
        "pub name: &'static str,",
        "pub function: HostFunction,",
        "pub const HOST_CALLS: &[HostCallSpec] = &[",
    ]:
        require(term in generated, f"generated table lost {term!r}")

    entries = generate_host_calls.host_call_entries(ROOT)
    gated = sum(1 for _, _, feature in entries if feature)
    emitted = len(re.findall(r"^\s*HostCallSpec \{", generated, re.MULTILINE))
    gates = len(re.findall(r'^\s*#\[cfg\(feature = "([^"]+)"\)\]', generated, re.MULTILINE))
    require(
        emitted == len(entries),
        f"generated table has {emitted} entries, catalog yields {len(entries)}",
    )
    require(
        gates == gated,
        f"generated table has {gates} cfg gates, catalog yields {gated} gated entries",
    )
    generated_order = re.findall(r'HostCallSpec \{ name: "([^"]+)"', generated)
    require(
        generated_order == [name for name, _, _ in entries],
        "generated table must follow the catalog entry order",
    )


def validate_derived_count() -> None:
    api_tests = read(API_TESTS)
    require(
        not STALE_COUNT_RE.search(api_tests),
        "api_tests.rs still hardcodes a 557/529 host-call count",
    )
    require(
        DERIVED_ASSERT in api_tests,
        "api_tests.rs must derive the registration count from HOST_CALLS.len()",
    )
    for path in sorted((ROOT / "packages" / "spectra-api" / "src").glob("*.rs")):
        match = STALE_COUNT_RE.search(path.read_text(encoding="utf-8"))
        require(
            match is None,
            f"{path.relative_to(ROOT)} still hardcodes a 557/529 host-call count",
        )


def validate_counts() -> tuple[int, int]:
    with generate_host_calls.catalog_path(ROOT).open("rb") as handle:
        catalog = tomllib.load(handle)
    entries = [entry for entry in catalog["entry"] if entry.get("rust_symbol")]
    gated = sum(1 for entry in entries if entry.get("cfg_feature"))
    return len(entries), len(entries) - gated


def validate_crate_tests() -> None:
    run_command([cargo_command(), "test", "-p", "spectra-api"])


def validate_planning() -> None:
    backlog = read("docs/roadmap-backlog.md")
    block = backlog.split(
        "## R-3208 Generate the Host-Call Table and Remove the Manual Count", 1
    )[1].split("## R-3209", 1)[0]
    for term in ["Status: `complete`", "scripts/validate_r3208_hostcall_generation.py"]:
        require(term in block, f"backlog R-3208 missing {term}")
    require(
        "validate_r3208_hostcall_generation.py" in read("run_tests.ps1"),
        "run_tests.ps1 must run R-3208",
    )


def main() -> None:
    validate_generator()
    validate_generated_file()
    validate_derived_count()
    total, always_on = validate_counts()
    validate_crate_tests()
    validate_planning()
    print(
        "validated R-3208 host-call generation: "
        f"{total} catalog bindings ({always_on} always on, {total - always_on} feature-gated)"
    )


if __name__ == "__main__":
    main()
