#!/usr/bin/env python3
"""Validate the generated mid-end host-call lowering tables (R-3207).

The seven lowering tables are rendered by
``scripts/generate_lowering_tables.py`` from
``packages/spectra-contract/catalog/stdlib.toml``.  This validator proves the
checked-in files are that rendering - byte for byte - and that no hand-written
match arm survives next to the generated block:

1. ``--check`` reports no stale table;
2. ``--from-source`` matches the embedded ``LAYOUT`` (the presentation data was
   extracted from the legacy tables, not retyped);
3. every generated file carries the do-not-edit header;
4. the arm sequence of each file equals the generator's layout, so an arm added
   by hand outside the generated block is rejected;
5. the entry points the hand-written gate calls still exist in the generated
   files;
6. ``cargo test -p spectra-midend`` passes.

Usage:
    python scripts/validate_r3207_lowering_generation.py
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import generate_lowering_tables  # noqa: E402

GATE = "midend/src/lowering_std_host.rs"
HEADER_MARKER = "// @generated by scripts/generate_lowering_tables.py - do not edit manually."
CHECK_COMMAND = "python scripts/generate_lowering_tables.py --check"
ARM_RE = re.compile(r'^(\s*)\("([\w.]+)", "(\w+)"\) =>', re.MULTILINE)
ENTRY_POINT_RE = re.compile(r"lookup_(?:std_api_host_function|std_host_module_function|std_host_group_\w+)")


def cargo_command() -> str:
    cargo = "cargo.exe" if sys.platform.startswith("win") else "cargo"
    home = Path(os.environ.get("USERPROFILE") or os.environ.get("HOME") or "")
    candidate = home / ".cargo" / "bin" / cargo
    return str(candidate) if candidate.exists() else "cargo"


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def fail(message: str) -> None:
    print(f"R-3207 validation failed: {message}", file=sys.stderr)
    raise SystemExit(1)


def require(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def run_command(args: list[str]) -> None:
    completed = subprocess.run(
        args,
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if completed.returncode != 0:
        fail(f"command {' '.join(args)} failed:\n{completed.stdout}")


def run_generator(*args: str) -> None:
    completed = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "generate_lowering_tables.py"), *args],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    require(
        completed.returncode == 0,
        f"generate_lowering_tables.py {' '.join(args)} failed:\n{completed.stdout}",
    )


def validate_staleness() -> None:
    run_generator("--check")
    run_generator("--from-source")


def validate_generated_files() -> None:
    rendered = generate_lowering_tables.render_all(ROOT)
    require(
        len(rendered) == len(generate_lowering_tables.LAYOUT) + 1,
        "the generator must own the six group tables plus the numeric dispatcher",
    )
    for relative, text in rendered.items():
        generated = read(relative)
        require(
            generated == text,
            f"{relative} is not the generator's rendering; run `{CHECK_COMMAND}`",
        )
        require(
            generated.startswith(HEADER_MARKER),
            f"{relative} must start with the do-not-edit header",
        )
        require(
            CHECK_COMMAND in generated,
            f"{relative} must name the --check command in its header",
        )


def validate_no_handwritten_arms() -> None:
    catalog = generate_lowering_tables.load_catalog(ROOT)
    for layout in generate_lowering_tables.LAYOUT:
        generated = read(layout.path)
        arms = [(module, function) for _, module, function in ARM_RE.findall(generated)]
        expected = [
            (group.module, item.split("@", 1)[0])
            for group in layout.groups
            for item in group.names.split()
        ]
        require(
            arms == expected,
            f"{layout.path} does not contain exactly the {len(expected)} generated arms "
            f"in layout order ({len(arms)} found)",
        )
        require(
            generated.count("match (module, function)") == 1,
            f"{layout.path} must hold a single generated match block",
        )
        literals = sum(
            1
            for group in layout.groups
            for item in group.names.split()
            if generate_lowering_tables.arm_style(
                layout, catalog, group.module, item.split("@", 1)[0]
            )
            == generate_lowering_tables.STYLE_STRUCT
        )
        require(
            generated.count("HostFunctionDescriptor {") == literals,
            f"{layout.path} has {generated.count('HostFunctionDescriptor {')} descriptor "
            f"literals outside the generated block (expected {literals})",
        )
    numeric = read(generate_lowering_tables.NUMERIC_PATH)
    require(
        numeric.startswith(HEADER_MARKER),
        f"{generate_lowering_tables.NUMERIC_PATH} must start with the do-not-edit header",
    )
    require(
        not ARM_RE.search(numeric),
        f"{generate_lowering_tables.NUMERIC_PATH} must not contain a hand-written descriptor table",
    )


def validate_entry_points() -> None:
    """The hand-written gate must still resolve the lowering entry points.

    ``lowering_std_host.rs`` is not generated; it keeps calling the tables by
    name, so every ``lookup_*`` it references must still be defined somewhere in
    ``midend/src`` (the generated tables own most of them).
    """
    gate = read(GATE)
    definitions: set[str] = set()
    for path in sorted((ROOT / "midend" / "src").glob("*.rs")):
        definitions |= set(re.findall(r"fn (lookup_\w+)", path.read_text(encoding="utf-8")))
    called = set(ENTRY_POINT_RE.findall(gate))
    missing = sorted(called - definitions)
    require(
        not missing,
        f"{GATE} calls lowering entry points that no midend source defines: {missing}",
    )
    generated_definitions = set(
        re.findall(r"pub\(crate\) fn (lookup_\w+)", read(generate_lowering_tables.NUMERIC_PATH))
    ) | {
        entry
        for layout in generate_lowering_tables.LAYOUT
        for entry in re.findall(r"pub\(crate\) fn (lookup_\w+)", read(layout.path))
    }
    require(
        generated_definitions,
        "the generated tables define no lowering entry point",
    )


def validate_crate_tests() -> None:
    run_command([cargo_command(), "test", "-p", "spectra-midend"])


def validate_planning() -> None:
    backlog = read("docs/roadmap-backlog.md")
    block = backlog.split("## R-3207 Generate Midend Lowering Tables from the Catalog", 1)[1].split(
        "## R-3208", 1
    )[0]
    for term in ["Status: `complete`", "scripts/validate_r3207_lowering_generation.py"]:
        require(term in block, f"backlog R-3207 missing {term}")
    require(
        "validate_r3207_lowering_generation.py" in read("run_tests.ps1"),
        "run_tests.ps1 must run R-3207",
    )


def main() -> None:
    validate_staleness()
    validate_generated_files()
    validate_no_handwritten_arms()
    validate_entry_points()
    validate_crate_tests()
    validate_planning()
    arms = sum(
        len(group.names.split())
        for layout in generate_lowering_tables.LAYOUT
        for group in layout.groups
    )
    print(
        "validated R-3207 lowering generation: "
        f"{arms} generated arms across {len(generate_lowering_tables.LAYOUT) + 1} tables"
    )


if __name__ == "__main__":
    main()
